#let terms = (
  "Asset": [Termine inglese che si traduce in "risorsa"[cite: 7]. Nel contesto dello standard EN18031, gli asset sono dati in equipaggiamenti il cui accesso o manipolazione può influenzare l'apparecchiatura[cite: 8].],
  "Cybersecurity": [Pratica di proteggere persone, sistemi e dati dagli attacchi informatici tramite tecnologie e regole[cite: 9]. Il RED DA impone requisiti minimi ai dispositivi radio per proteggere gli asset da attacchi esterni.],
  "Decision Tree": [Struttura ad albero usata per determinare il successo, il fallimento o la non applicabilità di un requisito per un determinato asset.],
  "Dispositivo radio connesso a internet": [Apparecchio con qualunque percorso per il passaggio di dati trasmessi o ricevuti dalla rete.],
  "DT": [Abbreviazione di Decision Tree.],
  "EN18031": [Serie ufficiale di standard per il RED DA, composta da tre parti: EN18031-1 (3.3 d), EN18031-2 (3.3 e) e EN18031-3 (3.3 f).],
  "IoT": [Abbreviazione di Internet of Things, ovvero l'estensione di internet al mondo degli oggetti e dei luoghi concreti.],
  "RED DA": [Abbreviazione di Radio Equipment Delegated Act, legislazione europea per garantire requisiti di salute e sicurezza degli apparecchi radio.],
  "VE": [Abbreviazione di Verbale Esterno.],
  "VI": [Abbreviazione di Verbale Interno.],
  "Dashboard": [Applicazione o schermata di un sistema operativo che unisce vari strumenti, consentendo la loro visualizzazione in base alle esigenze di gestione.],
  "Agile": [Approccio di gestione dei progetti iterativo e incrementale che punta sulla flessibilità, collaborazione continua e rilasci rapidi. Suddivide il lavoro in cicli brevi(sprint) per adattarsi rapidamente ai cambiamenti.],
  "Attore": [Un attore può essere una persona, un'azienda, un organizzazione, un programma o un sistema del computer (sia hardware che software) che interagisce con un sistema per raggiungere un obbiettivo.],
  "Backend": [È l'infrastruttura base del software; quella che riceve gli input di dati, li archivia eventualmente in un database e, in generale, elabora le richieste dell'utente per poi comunicare un qualche tipo di output al frontend.],
  "FrontEnd": [È la parte di un applicativo, di un servizio o di una piattaforma che gestisce l'interazione con l'utente. Sostanzialmente il frontend si occupa di ricevere dall'utilizzatore un flusso di dati.],
  "Nodo": [In questo contesto il nodo è un elemento del decisione tree che può contenere una domanda per verificare il corretto passaggio di un requisito. Oppure può contenere l'esito finale della valutazione del decision tree.],
  "Requisiti": [In questo contesto con requisiti intendiamo i vari controlli che sono richiesti ad un dispositivo radio per poter essere considerato conforme alla normativa RED DA.],
  "Use Case": [Tradotto dall'inglese = caso d'uso, è un elenco di azioni o fasi che in genere definiscono le interazioni tra un ruolo (in questo caso noto come attore) e un sistema per raggiungere un obbiettivo.],

)