#let terms = (
  "Asset": [Termine inglese che si traduce in "risorsa"[cite: 7]. Nel contesto dello standard EN18031, gli asset sono dati in equipaggiamenti il cui accesso o manipolazione può influenzare l'apparecchiatura[cite: 8].],
  "Cybersecurity": [Pratica di proteggere persone, sistemi e dati dagli attacchi informatici tramite tecnologie e regole[cite: 9]. Il RED DA impone requisiti minimi ai dispositivi radio per proteggere gli asset da attacchi esterni.],
  "Decision Tree": [Struttura ad albero usata per determinare il successo, il fallimento o la non applicabilità di un requisito per un determinato asset.],
  "Dispositivo radio connesso a internet": [Apparecchio con qualunque percorso per il passaggio di dati trasmessi o ricevuti dalla rete.],
  "DT": [Abbreviazione di Decision Tree.],
  "EN18031": [Serie ufficiale di standard per il RED DA, composta da tre parti: EN18031-1 (3.3 d), EN18031-2 (3.3 e) e EN18031-3 (3.3 f).],
  "IoT": [Abbreviazione di Internet of Things, ovvero l'estensione di internet al mondo degli oggetti e dei luoghi concreti.],
  "RED DA": [Abbreviazione di Radio Equipment Delegated Act, legislazione europea per garantire requisiti di salute e sicurezza degli apparecchi radio.],
  "VE": [Abbreviazione di Verbale Esterno.],
  "VI": [Abbreviazione di Verbale Interno.],
  "Dashboard": [Applicazione o schermata di un sistema operativo che unisce vari strumenti, consentendo la loro visualizzazione in base alle esigenze di gestione.],
  "Agile": [Approccio di gestione dei progetti iterativo e incrementale che punta sulla flessibilità, collaborazione continua e rilasci rapidi. Suddivide il lavoro in cicli brevi(sprint) per adattarsi rapidamente ai cambiamenti.],
  "Attore": [Un attore può essere una persona, un'azienda, un organizzazione, un programma o un sistema del computer (sia hardware che software) che interagisce con un sistema per raggiungere un obbiettivo.],
  "Backend": [È l'infrastruttura base del software; quella che riceve gli input di dati, li archivia eventualmente in un database e, in generale, elabora le richieste dell'utente per poi comunicare un qualche tipo di output al frontend.],
  "FrontEnd": [È la parte di un applicativo, di un servizio o di una piattaforma che gestisce l'interazione con l'utente. Sostanzialmente il frontend si occupa di ricevere dall'utilizzatore un flusso di dati.],
  "Nodo": [In questo contesto il nodo è un elemento del decisione tree che può contenere una domanda per verificare il corretto passaggio di un requisito. Oppure può contenere l'esito finale della valutazione del decision tree.],
  "Requisiti": [In questo contesto con requisiti intendiamo i vari controlli che sono richiesti ad un dispositivo radio per poter essere considerato conforme alla normativa RED DA.],
  "Use Case": [Tradotto dall'inglese = caso d'uso, è un elenco di azioni o fasi che in genere definiscono le interazioni tra un ruolo (in questo caso noto come attore) e un sistema per raggiungere un obbiettivo.],
  "RTB (Requirements and Technology Baseline)": [Prima revisione di avanzamento del progetto didattico, focalizzata sull'approvazione dei requisiti e della base tecnologica.],
  "PB (Product Baseline)": [Seconda e ultima revisione di avanzamento, focalizzata sul rilascio del prodotto software completo, testato e corredato di manuali.],
  "Milestone": [Traguardo intermedio nello sviluppo del progetto che segna il completamento di una fase importante o il raggiungimento di un obiettivo chiave.],
  "Way of Working (WoW)": [Insieme di regole, convenzioni e processi adottati dal gruppo di lavoro per collaborare in modo efficace ed efficiente.],
  "Stakeholder": [Qualsiasi individuo, gruppo o organizzazione che ha un interesse o è coinvolto nello svolgimento e nel successo del progetto (es. team, docenti, azienda proponente).],
  "Proponente": [Entità, persona o azienda che propone il capitolato d'appalto e commissiona lo sviluppo del progetto.],
  "Requisito Funzionale": [Descrive uno specifico comportamento o una funzione che il sistema software deve essere in grado di compiere.],
  "Requisito Qualitativo": [Definisce un attributo di qualità che il sistema deve possedere per essere accettabile (es. prestazioni elevate, sicurezza, usabilità).],
  "Requisito di Vincolo": [Restrizione tecnologica, legislativa o organizzativa che limita le scelte di sviluppo del team (es. uso obbligatorio di uno specifico linguaggio di programmazione).],
  "Metrica": [Misura quantitativa utilizzata per valutare la qualità del prodotto software, l'efficienza dei processi adottati o il raggiungimento di uno specifico obiettivo.],
  "PDCA": [Acronimo di Plan-Do-Check-Act. È un ciclo iterativo utilizzato per il controllo e il miglioramento continuo dei processi.],
  "Test di Unità": [Tipologia di test volta a verificare il corretto funzionamento di singole e ridotte unità di codice (es. una funzione) in totale isolamento.],
  "Test di Sistema": [Tipologia di test condotta sull'intero sistema software integrato per valutarne la conformità ai requisiti architetturali e globali.],
  "Typst": [Linguaggio di markup e sistema di composizione tipografica utilizzato dal gruppo per scrivere e generare automaticamente in formato PDF i documenti di progetto.],
  "Vulnerabilità": [Debolezza intrinseca in un sistema, in un'applicazione o in una rete che può essere sfruttata da una minaccia informatica per causare un danno (molto rilevante per la tematica RED DA).],
  "Scrum": [Framework di sviluppo agile che organizza il lavoro in cicli iterativi e incrementali (sprint), basandosi su ruoli, eventi e artefatti definiti per favorire la collaborazione e il miglioramento continuo del team.],
  "Analisi dei requisiti": [Processo di analisi dei requisiti per definire cosa fare prima del reale sviluppo.],
  "Sprint": [L'unità temporale base (solitamente 1-4 settimane) in cui viene creato un avanzamento di lavoro.],
  "Analisi dei rischi": [Classificazione dei rischi rispettivamente tecnologici (RT), organizzativi (RO), e individuali (RI).],
  "RT": [Rischio Tecnologico: Rischio legato alle tecnologie scelte per lo sviluppo del progetto, come incompatibilità, mancanza di esperienza o limitazioni degli strumenti.],
  "RO": [Rischio Organizzativo: Rischio legato all'organizzazione del progetto, come ritardi nella pianificazione, errori di stima o problemi di comunicazione interna.],
  "RI": [Rischio Individuale: Rischio legato ai singoli membri del team, come assenze improvvise, conflitti interpersonali o carenza di specifiche competenze.],
  "ACM": [Abbreviazione di Access Control Mechanism (meccanismo di controllo degli accessi). Insieme di requisiti dello standard EN 18031-1 che disciplinano come l'apparecchiatura gestisce l'accesso delle entità agli asset di sicurezza e di rete.],
  "AUM": [Abbreviazione di Authentication Mechanism (meccanismo di autenticazione). Insieme di requisiti dello standard EN 18031-1 relativi alla verifica dell'identità delle entità che interagiscono con l'apparecchiatura.],
  "Indice di Gulpease": [Valuta la leggibilità di un testo in lingua italiana. Un valore basso indica un testo eccessivamente complesso rispetto al target di riferimento.],
  "Planned Value (PV)": [Esprime il valore del lavoro pianificato da completare entro una determinata data.],
  "Earned Value (EV)": [Esprime il valore del lavoro effettivamente completato, in conformità con il budget previsto.],
  "Actual Cost (AC)": [Indica il costo totale effettivamente sostenuto fino alla data corrente.],
  "Schedule Performance Index (SPI)": [Misura l'efficienza temporale del progetto.],
  "Cost Performance Index (CPI)": [Misura l'efficienza economica del progetto.],
  "Estimate at Completion (EAC)": [Fornisce la proiezione del costo totale finale del progetto sulla base della performance attuale.],
  "Estimate to Complete (ETC)": [Stima il costo necessario per completare il lavoro rimanente.],
  "Requirements Stability Index (RSI)": [Misura la stabilità dei requisiti nel tempo, valutando l'impatto di modifiche, cancellazioni e aggiunte rispetto al set iniziale.],
  "Budget at Completion (BAC)": [Budget complessivo previsto per il completamento del progetto, espresso in termini economici o orari. Costituisce la base di calcolo delle metriche di Earned Value Management (PV, EV, EAC).],
  "Time Efficiency": [Indica il rapporto tra il tempo pianificato e quello effettivamente impiegato.],
  "Quality Metrics Satisfied": [Rappresenta la percentuale complessiva delle metriche di qualità che rientrano nei range accettabili definiti nelle Norme di Progetto.],
)