#let terms = (
  "Asset": [Termine inglese che si traduce in "risorsa". Nel contesto dello standard EN18031, gli asset sono dati in equipaggiamenti il cui accesso o manipolazione può influenzare l'apparecchiatura.],
  "Cybersecurity": [Pratica di proteggere persone, sistemi e dati dagli attacchi informatici tramite tecnologie e regole. Il RED DA impone requisiti minimi ai dispositivi radio per proteggere gli asset da attacchi esterni.],
  "Decision Tree": [Struttura ad albero usata per determinare il successo, il fallimento o la non applicabilità di un requisito per un determinato asset.],
  "Dispositivo radio connesso a internet": [Apparecchio con qualunque percorso per il passaggio di dati trasmessi o ricevuti dalla rete.],
  "DT": [Abbreviazione di Decision Tree.],
  "EN18031": [Serie ufficiale di standard per il RED DA, composta da tre parti: EN18031-1 (3.3 d), EN18031-2 (3.3 e) e EN18031-3 (3.3 f).],
  "IoT": [Acronimo di Internet of Things (Internet delle Cose). Paradigma tecnologico che descrive reti di oggetti fisici dotati di sensori, software e connettività, capaci di raccogliere e scambiare dati attraverso Internet. Nel contesto normativo EN18031, i dispositivi IoT sono tra i principali soggetti a valutazione di conformità in quanto esposti ad attacchi informatici attraverso le proprie interfacce di rete.],
  "RED DA": [Atto Delegato della Commissione Europea che estende la Direttiva RED (2014/53/UE) imponendo requisiti obbligatori di sicurezza informatica per i dispositivi radio immessi sul mercato europeo. Obbligatorio dal 1° agosto 2025, richiede che i dispositivi radio siano conformi allo standard EN18031 per quanto riguarda la protezione della rete, dei dati personali e la prevenzione delle frodi.],
  "VE": [Abbreviazione di Verbale Esterno.],
  "VI": [Abbreviazione di Verbale Interno.],
  "Dashboard": [Applicazione o schermata di un sistema operativo che unisce vari strumenti, consentendo la loro visualizzazione in base alle esigenze di gestione.],
  "Agile": [Approccio di gestione dei progetti iterativo e incrementale che punta sulla flessibilità, collaborazione continua e rilasci rapidi. Suddivide il lavoro in cicli brevi (sprint) per adattarsi rapidamente ai cambiamenti.],
  "Attore": [Entità esterna al sistema — persona, organizzazione, programma o sistema informatico — che interagisce con esso per raggiungere un obiettivo specifico. Non fa parte del sistema, ma vi si interfaccia scambiando informazioni.],
  "Backend": [È l'infrastruttura base del software; quella che riceve gli input di dati, li archivia eventualmente in un database e, in generale, elabora le richieste dell'utente per poi comunicare un qualche tipo di output al frontend.],
  "Frontend": [È la parte di un applicativo, di un servizio o di una piattaforma che gestisce l'interazione con l'utente. Sostanzialmente il frontend si occupa di ricevere dall'utilizzatore un flusso di dati.],
  "Nodo": [Elemento costitutivo di un Decision Tree. Può essere un nodo di decisione, contenente una domanda a cui l'utente deve rispondere per determinare il percorso di valutazione successivo, oppure un nodo foglia, che rappresenta l'esito finale della valutazione (Pass, Fail o Not Applicable).],
  "Requisiti": [Capacità o condizioni che il sistema software deve soddisfare per rispondere ai bisogni della proponente e ai vincoli normativi applicabili. Includono sia funzionalità che il sistema deve implementare (requisiti funzionali) sia proprietà che deve possedere (requisiti qualitativi e di vincolo).],
  "Use Case": [Descrizione formale di un'interazione tra uno o più attori e il sistema, finalizzata al raggiungimento di un obiettivo specifico. Include precondizioni, scenario principale, scenari alternativi e postcondizioni. Strumento fondamentale per la raccolta e la formalizzazione dei requisiti funzionali.],
  "Analisi dei Requisiti": [Processo sistematico di individuazione, classificazione, formalizzazione e tracciamento delle necessità espresse dalla proponente e dei vincoli normativi, volto a definire in modo univoco le funzionalità e le qualità che il sistema software deve possedere prima dell'avvio delle attività di progettazione e sviluppo.],
  "AdR": [Acronimo di Analisi dei Requisiti.],
  "Norme di Progetto": [Documento interno, redatto dall'Amministratore, che definisce il Way of Working del gruppo, stabilendo l'insieme di regole operative, convenzioni, standard tecnici e metriche quantitative da adottare per garantire l'uniformità dei processi.],
  "NdP": [Acronimo di Norme di Progetto.],
  "Piano di Progetto": [Documento esterno, redatto dal Responsabile, che stabilisce la pianificazione temporale delle attività suddivisa in sprint, la gestione delle risorse, la ripartizione dei costi e l'analisi preventiva e il monitoraggio dei rischi.],
  "PdP": [Acronimo di Piano di Progetto.],
  "Piano di Qualifica": [Documento esterno, redatto dall'Amministratore, che specifica gli obiettivi di qualità del processo e del prodotto software, descrive il cruscotto di valutazione delle metriche e definisce le strategie di testing e i criteri di validazione.],
  "PdQ": [Acronimo di Piano di Qualifica.],
  "Verbale Esterno": [Documento di coordinamento ufficiale che registra l'esito dei meeting, i chiarimenti e le decisioni concordate con soggetti esterni al team, quali l'azienda proponente o il committente.],
  "Verbale Interno": [Documento di coordinamento che riporta il resoconto delle riunioni interne al team di progetto, registrando l'ordine del giorno, lo svolgimento della discussione, le decisioni prese e il tracciamento delle attività future (TODO).],
  "Requirements and Technology Baseline": [Prima revisione di avanzamento del progetto didattico, focalizzata sull'approvazione dei requisiti e della base tecnologica.],
  "RTB": [Acronimo di Requirements and Technology Baseline.],
  "Product Baseline": [Seconda e ultima revisione di avanzamento, focalizzata sul rilascio del prodotto software completo, testato e corredato di manuali.],
  "PB": [Acronimo di Product Baseline.],
  "Milestone": [Traguardo intermedio nello sviluppo del progetto che segna il completamento di una fase importante o il raggiungimento di un obiettivo chiave.],
  "Way of Working": [Insieme di regole, convenzioni e processi adottati dal gruppo di lavoro per collaborare in modo efficace ed efficiente.],
  "WoW": [Acronimo di Way of Working.],
  "Stakeholder": [Qualsiasi individuo, gruppo o organizzazione che ha un interesse o è coinvolto nello svolgimento e nel successo del progetto (es. team, docenti, azienda proponente).],
  "Proponente": [Entità, persona o azienda che propone il capitolato d'appalto e commissiona lo sviluppo del progetto.],
  "Committente": [L'organo valutatore del progetto didattico, composto dal corpo docente del corso di Ingegneria del Software.],
  "PDCA": [Ciclo iterativo (Plan-Do-Check-Act) utilizzato per il controllo e il miglioramento continuo dei processi.],
  "Scrum": [Framework agile per la gestione di progetti software che organizza il lavoro in iterazioni brevi e a durata fissa chiamate sprint. Prevede ruoli definiti (Product Owner, Scrum Master, Development Team), artefatti strutturati (Product Backlog, Sprint Backlog) e cerimonie ricorrenti (Sprint Planning, Daily Scrum, Sprint Review, Retrospettiva). Favorisce la trasparenza, l'ispezione continua e l'adattamento rapido ai cambiamenti.],
  "Sprint": [Iterazione di sviluppo a durata fissa (tipicamente una o due settimane) al termine della quale il team produce un incremento di prodotto verificabile e potenzialmente rilasciabile. È l'unità base del framework Scrum: ogni sprint inizia con una fase di pianificazione e si conclude con una revisione del lavoro svolto e una retrospettiva.],
  "Analisi dei rischi": [Processo sistematico di identificazione, valutazione e pianificazione delle risposte ai potenziali eventi negativi che potrebbero compromettere il progetto. I rischi vengono classificati in tecnologici (RT), organizzativi (RO) e individuali (RI), ciascuno associato a una probabilità di occorrenza e a un indice di gravità, e gestiti con misure preventive o correttive.],
  "RT": [Abbreviazione di Rischio Tecnologico.],
  "RO": [Abbreviazione di Rischio Organizzativo.],
  "RI": [Abbreviazione di Rischio Individuale.],
  "Template": [Modello o schema strutturale predefinito e condiviso dal team per garantire l'uniformità grafica, stilistica e formale dei documenti prodotti.],
  "Typst": [Linguaggio di markup e sistema di composizione tipografica utilizzato dal gruppo per scrivere e generare automaticamente in formato PDF i documenti di progetto.],
  "Vulnerabilità": [Debolezza intrinseca in un sistema, in un'applicazione o in una rete che può essere sfruttata da una minaccia informatica per causare un danno (molto rilevante per la tematica RED DA).],
  "Requisito Funzionale": [Descrive uno specifico comportamento o una funzione che il sistema software deve essere in grado di compiere.],
  "Requisito Qualitativo": [Definisce un attributo di qualità che il sistema deve possedere per essere accettabile (es. prestazioni elevate, sicurezza, usabilità).],
  "Requisito di Vincolo": [Restrizione tecnologica, legislativa o organizzativa che limita le scelte di sviluppo del team (es. uso obbligatorio di uno specifico linguaggio di programmazione).],
  "Requisito Desiderabile": [Tipologia di requisito non strettamente obbligatorio ma che porta un valore aggiunto significativo al prodotto, la cui implementazione è subordinata al completamento dei requisiti obbligatori.],
  "Requisito Obbligatorio": [Requisito fondamentale e imprescindibile per la validazione del prodotto, concordato direttamente con la proponente.],
  "Requisito Opzionale": [Requisito a bassa priorità che rappresenta una funzionalità di contorno o un miglioramento futuro, implementato solo in caso di avanzo di tempo o budget.],
  "Automated EN18031 Compliance Verification": [Nome del capitolato di progetto scelto. Indica il sistema software sviluppato dal gruppo Coderius per automatizzare il processo di valutazione della conformità dei dispositivi radio allo standard EN 18031.],
  "Proof of Concept": [Realizzazione software preliminare finalizzata a dimostrare la fattibilità tecnica della soluzione architetturale scelta e l'interoperabilità delle tecnologie adottate durante la fase di RTB.],
  "PoC": [Acronimo di Proof of Concept.],
  "Mock-up": [Rappresentazione visiva o interfaccia grafica preliminare e abbozzata del software, utilizzata per mostrare alla proponente l'organizzazione delle funzionalità e raccogliere feedback.],
  "Walkthrough": [Metodo di analisi statica manuale basato sulla lettura e analisi critica e approfondita di un intero documento o file, utilizzato principalmente a fronte di anomalie complesse non collocate a priori.],
  "Metrica": [Misura quantitativa utilizzata per valutare la qualità del prodotto software, l'efficienza dei processi adottati o il raggiungimento di uno specifico obiettivo.],
  "Indice di leggibilità Gulpease": [Metrica di qualità documentale tarata sulla lingua italiana che valuta la leggibilità di un testo in base alla lunghezza delle parole e delle frasi su una scala da 0 a 100.],
  "Test di Unità": [Tipologia di test volta a verificare il corretto funzionamento di singole e ridotte unità di codice (es. una funzione) in totale isolamento.],
  "Test di Integrazione": [Tipologia di test che verifica la corretta interazione tra moduli o componenti distinti del sistema, accertando che le interfacce tra le parti si comportino come previsto una volta integrate.],
  "Test di Sistema": [Tipologia di test condotta sull'intero sistema software integrato per valutarne la conformità ai requisiti architetturali e globali.],
  "Test di Accettazione": [Fase finale del processo di testing in cui la proponente o gli utenti finali verificano che il sistema soddisfi i requisiti contrattuali e le aspettative concordate, validando i flussi operativi completi in scenari d'uso reali.],
  "Branch Coverage": [Metrica quantitativa di prodotto che esprime la percentuale di rami decisionali del codice effettivamente coperti ed eseguiti dai test automatizzati.],
  "BC": [Abbreviazione di Branch Coverage.],
  "Statement Coverage": [Metrica quantitativa che indica la percentuale di singole istruzioni del codice sorgente che vengono effettivamente eseguite durante l'esecuzione dei test.],
  "SC": [Abbreviazione di Statement Coverage.],
  "Test Pass Rate": [Metrica quantitativa che misura la percentuale di test d'unità, di integrazione o di sistema superati con successo rispetto al totale dei test eseguiti.],
  "TPR": [Abbreviazione di Test Pass Rate.],
  "Coupling": [Indice quantitativo che misura il grado di interconnessione, dipendenza e accoppiamento reciproco tra i diversi moduli o componenti del sistema software.],
  "Afferent": [Classi esterne al modulo corrente che dipendono dalle classi interne al modulo stesso, utilizzate per il calcolo dell'Indice di Instabilità.],
  "Efferent": [Classi esterne al modulo corrente da cui le classi interne al modulo dipendono, utilizzate per il calcolo dell'Indice di Instabilità.],
  "Instability Index": [Metrica quantitativa che misura la resilienza di un modulo software al cambiamento, calcolata tramite il rapporto tra classi Efferent e Afferent.],
  "Cyclomatic Complexity": [Metrica che quantifica la complessità logica di un frammento di codice contando il numero di percorsi linearmente indipendenti attraverso il suo grafo di controllo.],
  "Linee di codice": [Metrica quantitativa elementare che conta il numero totale di righe di testo all'interno di un file sorgente, utilizzata come indicatore della dimensione del software.],
  "Numero di parametri per funzione": [Metrica di progettazione che misura il numero di argomenti accettati in input da una singola funzione, utilizzata per monitorare la complessità e la manutenibilità del codice.],
  "Code Smell": [Metrica quantitativa che misura la densità di potenziali problemi strutturali, imperfezioni di design o violazioni delle buone pratiche all'interno del codice sorgente.],
  "Errori bloccanti": [Metrica di processo che quantifica il numero di anomalie critiche rilevate durante la fase di verifica che impediscono il corretto funzionamento delle funzioni principali del software.],
  "Percentuale di metriche soddisfatte": [Metrica globale di processo che esprime il rapporto tra il numero di metriche che rientrano nei range di accettazione stabiliti e il totale delle metriche monitorate.],
  "Tempo di risposta": [Metrica prestazionale che calcola l'intervallo temporale che intercorre tra l'invio di una richiesta da parte dell'utente e la ricezione dell'output corrispondente dal sistema.],
  "GitHub Actions": [Servizio di automazione integrato in GitHub utilizzato per implementare pipeline di Continuous Integration, ad esempio per la compilazione automatica dei file sorgente Typst in PDF ad ogni merge.],
  "GitHub Projects": [Strumento di gestione e pianificazione delle attività che permette di monitorare l'avanzamento dei task attraverso tavole digitali e issue tracking.],
  "Issue Tracking System": [Sistema di tracciamento utilizzato su GitHub per registrare, assegnare, pianificare e monitorare l'evoluzione di singole unità di lavoro (issue).],
  "Pull Request": [Meccanismo collaborativo di GitHub che consente di sottoporre a verifica e revisione un insieme di modifiche contenute in un branch prima del merge.],
  "PR": [Abbreviazione di Pull Request.],
  "Backlog": [Sezione o colonna della Project Board Kanban in cui vengono raccolte tutte le attività identificate e pianificate per il progetto.],
  "Kanban": [Stile di gestione visuale delle attività utilizzato tramite la Project Board di GitHub per monitorare in tempo reale il transito dei task attraverso colonne di stato.],
  "Earned Value Management": [Metodologia di gestione di progetto che integra la misurazione dei tempi, dei costi e delle attività svolte per valutare l'andamento del budget.],
  "EVM": [Abbreviazione di Earned Value Management.],
  "Budget at Completion": [Valore monetario totale pianificato e stanziato per il completamento dell'intero progetto software.],
  "BAC": [Abbreviazione di Budget at Completion.],
  "Actual Cost": [Metrica economica cumulativa dell'Earned Value Management che indica il costo totale effettivamente sostenuto dal team fino alla data corrente del progetto.],
  "AC": [Abbreviazione di Actual Cost.],
  "Planned Value": [Valore del lavoro che era stato pianificato per essere completato entro una determinata data del progetto, espresso in termini di budget allocato.],
  "PV": [Abbreviazione di Planned Value.],
  "Earned Value": [Valore del lavoro effettivamente completato ed erogato fino a una determinata data, calcolato in rapporto al budget totale.],
  "EV": [Abbreviazione di Earned Value.],
  "Estimate at Completion": [Metrica economica cumulativa che esprime la proiezione del costo totale finale stimato del progetto sulla base dell'efficienza economica attuale.],
  "EAC": [Abbreviazione di Estimate at Completion.],
  "Estimate to Complete": [Metrica economica che rappresenta la stima del costo ancora necessario per portare a termine le attività rimanenti del progetto.],
  "ETC": [Abbreviazione di Estimate to Complete.],
  "Cost Performance Index": [Indice di efficienza economica dato dal rapporto tra Earned Value e Actual Cost.],
  "CPI": [Abbreviazione di Cost Performance Index.],
  "Schedule Performance Index": [Indice di efficienza temporale dato dal rapporto tra Earned Value e Planned Value.],
  "SPI": [Abbreviazione di Schedule Performance Index.],
  "Pass": [Esito conclusivo di un percorso in un Decision Tree che certifica la conformità del dispositivo radio al requisito normativo valutato. Viene assegnato quando tutte le risposte fornite dall'utente lungo il percorso soddisfano le condizioni richieste dallo standard EN18031.],
  "Fail": [Esito conclusivo di un percorso in un Decision Tree che segnala la non conformità del dispositivo radio al requisito normativo valutato. Viene assegnato quando almeno una delle condizioni richieste dallo standard EN18031 non risulta soddisfatta dalle risposte fornite dall'utente.],
  "Not Applicable": [Esito conclusivo di un percorso in un Decision Tree che segnala l'inapplicabilità del requisito al dispositivo in esame. Si verifica quando il dispositivo non possiede le caratteristiche o le interfacce a cui il requisito si riferisce.],
  "NA": [Abbreviazione di Not Applicable.],
  "RED": [Direttiva europea 2014/53/UE (Radio Equipment Directive) che disciplina la messa in commercio dei dispositivi radio nell'Unione Europea, stabilendo requisiti essenziali in materia di sicurezza, compatibilità elettromagnetica e uso dello spettro radio. Con l'adozione di EN18031 come norma armonizzata, impone la verifica della conformità ai requisiti di sicurezza informatica.],
  "Esportazione": [Funzione del sistema che serializza i dati interni in un file leggibile esternamente. Il formato di output determina se il file è destinato all'elaborazione automatica da parte di altri sistemi o alla lettura e archiviazione da parte degli utenti.],
  "UML": [Acronimo di Unified Modeling Language. Linguaggio standard di modellazione visuale utilizzato nell'ingegneria del software per rappresentare struttura e comportamento di un sistema attraverso diagrammi. Fornisce notazioni grafiche organizzate in due famiglie: i diagrammi strutturali, che catturano l'organizzazione statica del sistema e i diagrammi comportamentali, che ne descrivono la dinamica.],
  "Estensione": [Relazione UML tra casi d'uso, indicata con «extend», che descrive un comportamento opzionale che si aggiunge al caso d'uso base solo al verificarsi di una condizione specifica. Permette di isolare i flussi opzionali o eccezionali in casi d'uso separati, separandoli dal flusso principale senza modificarne la struttura.],
  "Branch": [Linea di sviluppo parallela e indipendente all'interno di un repository Git, utilizzata per isolare lo sviluppo di nuove funzionalità, correzioni o esperimenti senza impattare il ramo principale del progetto.],
  "Merge": [In Git, operazione che incorpora la storia dei commit di un branch sorgente nel branch di destinazione,  rendendo effettive nel progetto principale le modifiche sviluppate in isolamento.],
  "Interfaccia": [Punto di interazione tra due sistemi o componenti software che definisce le modalità di comunicazione e scambio di informazioni tra di essi. Nel contesto normativo EN18031.],
  "Validazione": [Processo volto a verificare che il prodotto software corrisponda alle reali esigenze dell'utente finale e ai requisiti concordati con la proponente. La validazione giudica se il sistema risolve effettivamente il problema per cui è stato commissionato.],
  "Retrospettiva di Sprint": [Cerimonia Scrum collocata al termine di ogni sprint in cui il team analizza il proprio modo di lavorare, identifica cosa ha funzionato bene, cosa ha generato difficoltà e definisce azioni concrete di miglioramento da adottare nel ciclo successivo.],
  "Wi-Fi": [Tecnologia di comunicazione wireless basata sullo standard IEEE 802.11 che consente la connessione a reti locali senza l'uso di cavi. Nel contesto del progetto, rappresenta una delle possibili interfacce di rete di un dispositivo radio soggette a valutazione normativa secondo EN18031.],
  "Bluetooth": [Tecnologia di comunicazione wireless a corto raggio utilizzata per lo scambio di dati tra dispositivi nelle immediate vicinanze. Nel contesto normativo EN18031, può rappresentare un'interfaccia del dispositivo radio soggetta a valutazione in quanto potenziale vettore di accesso non autorizzato.],
  "Grafo": [Struttura dati composta da nodi collegati tra loro da archi orientati. Nel contesto del progetto, il grafo del Decision Tree rappresenta visivamente la struttura ad albero binario del processo decisionale, mostrando nodi di decisione, collegamenti etichettati Yes e No e nodi foglia con i rispettivi esiti.],
  "Nodo foglia": [Nodo terminale di un Decision Tree, privo di successori. Rappresenta l'esito conclusivo di un percorso decisionale: PASS, FAIL o NOT APPLICABLE.],
  "Nodo di decisione": [Nodo interno di un Decision Tree che contiene una domanda a cui l'utente deve rispondere durante la sessione di valutazione. Ogni nodo di decisione ha esattamente due rami in uscita, etichettati Yes e No, che conducono al nodo successivo nel percorso.],
  "Dipendenza": [Relazione tra due requisiti che vincola l'ordine o la condizione di valutazione: un requisito dipendente può essere valutato solo dopo che il requisito da cui dipende ha ottenuto un esito.],
  "Sessione di valutazione": [Unità di lavoro in cui l'utente valuta la conformità di un dispositivo radio allo standard EN18031, navigando i Decision Tree associati a ciascun asset e requisito e registrando risposte e giustificazioni.],
  "Sensibilità": [Attributo booleano di un asset che indica se le informazioni o le funzionalità che esso rappresenta sono di natura sensibile dal punto di vista della sicurezza o della privacy. Influenza la rilevanza dei requisiti normativi applicabili all'asset nel contesto della valutazione EN18031.],
  "Stato aggregato": [Valore sintetico calcolato dal sistema che rappresenta il risultato complessivo della valutazione di un dispositivo o di un asset, ottenuto combinando gli esiti di tutti i requisiti valutati. Può assumere i valori PASS, FAIL o NOT APPLICABLE ed è visualizzabile sia a livello di singolo asset sia a livello dell'intero dispositivo.],
  "Report di conformità": [Documento generato al termine di una sessione di valutazione completata, che riassume per ogni coppia asset-requisito l'esito ottenuto, l'esito aggregato del Decision Tree e il percorso logico seguito.],
  "Importazione": [Operazione che consente di caricare nel sistema dati strutturati provenienti da file esterni.],
  "Inclusione": [Relazione UML tra casi d'uso, indicata con lo stereotipo «include», che descrive una funzionalità eseguita obbligatoriamente come parte integrante del caso d'uso che la include. A differenza dell'estensione, l'inclusione non è opzionale: il caso d'uso incluso viene sempre eseguito quando il caso d'uso base è attivo.],
  "Specializzazione": [Relazione UML tra casi d'uso in cui un caso d'uso figlio eredita le caratteristiche del caso d'uso padre e ne restringe il comportamento per un contesto più specifico.],
  "Analisi statica": [Tecnica di verifica che esamina il codice sorgente o i documenti senza eseguire il programma, con l'obiettivo di individuare difetti, violazioni di convenzioni o problemi strutturali. Nel progetto viene applicata tramite strumenti automatici e revisioni manuali come il walkthrough.],
  "Analisi dinamica": [Tecnica di verifica che valuta il comportamento del sistema durante la sua esecuzione, attraverso l'esecuzione di test automatizzati su dati di input reali o simulati. Comprende i test di unità, di integrazione, di sistema e di accettazione.],
  "Test di regressione": [Insieme di test rieseguiti dopo una modifica al codice per verificare che le funzionalità preesistenti non abbiano subito regressioni, ovvero che le modifiche non abbiano introdotto nuovi difetti in parti del sistema precedentemente funzionanti.],
  "Issue": [Unità atomica di lavoro tracciata nel repository GitHub del progetto, che può rappresentare un'attività da svolgere, un difetto da correggere o una funzionalità da implementare.],
  "Commit": [Operazione Git che registra in modo permanente nello storico del repository un insieme coerente di modifiche apportate ai file del progetto. Ogni commit è associato a un messaggio descrittivo che ne sintetizza il contenuto e a un identificativo univoco che ne consente il tracciamento.],
  "Diario di bordo": [Documento periodico a carattere informativo che descrive lo stato di avanzamento del progetto in un determinato periodo, le attività svolte, le difficoltà incontrate e i task pianificati per il periodo successivo.],
  "Lettera di candidatura": [Documento formale con cui il gruppo ha manifestato la propria intenzione di partecipare al capitolato selezionato, dichiarando l'impegno in termini di risorse, costi e tempistiche previste per lo sviluppo del progetto.],
  "MPC": [Acronimo di Metrica di Qualità del Processo. Indica le misure quantitative definite nel Piano di Qualifica per valutare l'efficacia e l'efficienza dei processi adottati dal team, come l'aderenza al budget, il rispetto delle scadenze e la densità degli errori nella documentazione.],
  "MPD": [Acronimo di Metrica di Qualità del Prodotto. Indica le misure quantitative definite nel Piano di Qualifica per valutare le caratteristiche del software prodotto, come la copertura del codice, la complessità ciclomatica e l'accoppiamento tra moduli.],
  "Time Efficiency": [Metrica di processo che misura l'efficienza temporale del team, calcolata come rapporto tra il tempo stimato per il completamento di un'attività e il tempo effettivamente impiegato. Un valore pari a 1 indica piena corrispondenza tra stima e consuntivo; valori inferiori segnalano una tendenza alla sottostima sistematica.],
  "ACM": [Abbreviazione di Access Control Mechanism (meccanismo di controllo degli accessi). Insieme di requisiti dello standard EN 18031-1 che disciplinano come l'apparecchiatura gestisce l'accesso delle entità agli asset di sicurezza e di rete.],
  "AUM": [Abbreviazione di Authentication Mechanism (meccanismo di autenticazione). Insieme di requisiti dello standard EN 18031-1 relativi alla verifica dell'identità delle entità che interagiscono con l'apparecchiatura.],

)
