name: Pubblica Sito su GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
  workflow_run:
    workflows: ["Aggiorna Sito Documentazione"]
    types:
      - completed
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Scarica la repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      
      - name: Copia i documenti nel sito
        run: |
          mkdir -p website/docs
          
          if [ -d "Candidatura" ]; then cp -r Candidatura website/docs/; fi
          if [ -d "RTB" ]; then cp -r RTB website/docs/; fi
          if [ -d "PB" ]; then cp -r PB website/docs/; fi

      - name: Carica i file del sito
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website'

      - name: Pubblica online
        id: deployment
        uses: actions/deploy-pages@v4