name: Pubblica Sito su GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Scarica la repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Carica i file del sito
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website'

      - name: Pubblica online
        id: deployment
        uses: actions/deploy-pages@v4