name: Aggiorna Sito Documentazione

on:
  workflow_run:
    workflows: ["Compila Documenti Typst"]
    types:
      - completed
    branches: 
      - main

jobs:
  aggiorna-html:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Scarica la repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Esegui lo script Python
        run: python .github/update_website.py

      - name: Commit e Push delle modifiche
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: aggiornato index.html con i nuovi documenti [skip ci]"
          file_pattern: website/index.html